name: Angular CI with SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build --if-present

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=opuk-orbispas
            -Dsonar.sources=src
            -Dsonar.host.url=http://localhost:9006
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
